import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import ImageModal from '../components/ImageModal';
import './Projects.css';

function FiniteElementCodingCourseProjects() {
  const [modalState, setModalState] = useState({
    isOpen: false,
    imageSrc: '',
    imageAlt: ''
  });

  const openModal = (src, alt) => {
    setModalState({
      isOpen: true,
      imageSrc: src,
      imageAlt: alt
    });
  };

  const closeModal = () => {
    setModalState({
      isOpen: false,
      imageSrc: '',
      imageAlt: ''
    });
  };

  return (
    <div className="project-detail-page">
      <div className="project-detail-header">
        <Link to="/projects" className="back-button">← Back to Projects</Link>
        <h1>Finite Element Code Projects</h1>
        <p className="project-subtitle">Graduate class projects that involved creating custom FEM codes to predict thermal and elastic behaviors</p>
        
        <div className="project-image-gallery">
          <div className="gallery-image-container">
            <img 
              src={require('../images/Finite Element Code Elasticity.png')} 
              alt="Finite Element Code"
              className="gallery-image"
              onClick={() => openModal(require('../images/Finite Element Code Elasticity.png'), "Finite element code set up for elasticity")}
            />
          </div>
          <div className="gallery-image-container">
            <img 
              src={require('../images/ABAQUS.png')} 
              alt="Temperature distribution generated by ABAQUS"
              className="gallery-image"
              onClick={() => openModal(require('../images/ABAQUS.png'), "Temperature distribution generated by ABAQUS")}
            />
          </div>
          <div className="gallery-image-container">
            <img 
              src={require('../images/Von Mises Stress.png')} 
              alt="Mesh and Von Mises stress contours generated by MATLAB code"
              className="gallery-image"
              onClick={() => openModal(require('../images/Von Mises Stress.png'), "Mesh and Von Mises stress contours generated by MATLAB code")}
            />
          </div>
        </div>
      </div>

      <div className="project-detail-content">
        <div className="project-overview">
          <h2>Projects Overview</h2>
          <p>
            Developed custom finite element method (FEM) codes in MATLAB as part of graduate engineering coursework. 
            These projects focused on gaining an understanding of and implementing numerical methods to predict thermal and elastic behaviors of 
            basic engineering problems - providing me with direct experience regarding FEM theory and how its used in commercial analysis tools.
          </p>
        </div>

        <div className="project-details">
          <div className="pdf-container">
            <div className="pdf-controls">
              <a 
                href="/MAE 503 Project 1.pdf" 
                download 
                className="download-button"
              >
                <svg 
                  className="download-icon" 
                  width="16" 
                  height="16" 
                  viewBox="0 0 24 24" 
                  fill="currentColor"
                >
                  <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/>
                </svg>
                <strong>Download Thermal Project PDF</strong>
              </a>
            </div>
            <div className="pdf-viewer">
              <iframe
                src="/MAE 503 Project 1.pdf"
                title="FEM Thermal Project PDF"
                width="100%"
                height="600px"
                style={{ border: 'none' }}
              />
            </div>
          </div>

          <div className="pdf-container">
            <div className="pdf-controls">
              <a 
                href="/MAE 503 Project 2.pdf" 
                download 
                className="download-button"
              >
                <svg 
                  className="download-icon" 
                  width="16" 
                  height="16" 
                  viewBox="0 0 24 24" 
                  fill="currentColor"
                >
                  <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/>
                </svg>
                <strong>Download Elasticity Project PDF</strong>
              </a>
            </div>
            <div className="pdf-viewer">
              <iframe
                src="/MAE 503 Project 2.pdf"
                title="FEM Elastic Project PDF"
                width="100%"
                height="600px"
                style={{ border: 'none' }}
              />
            </div>
          </div>

          <div className="detail-section">
            <h3>Tools/Technologies Used</h3>
            <ul>
                <li>MATLAB</li>
                <li>ABAQUS</li>
                <li>Ansys</li>
              </ul>
          </div>

          <div className="detail-section">
            <h3>Skills Demonstrated</h3>
            <div className="skills-grid">
              <span className="skill-tag">Finite Element Method</span>
              <span className="skill-tag">Programming</span>
              <span className="skill-tag">Numerical Methods</span>
              <span className="skill-tag">Computational Mechanics</span>
              <span className="skill-tag">Thermal Analysis</span>
              <span className="skill-tag">Structural Analysis</span>
              <span className="skill-tag">Data Visualization</span>
              <span className="skill-tag">Technical Writing</span>
            </div>
          </div>

          <div className="detail-section">
            <h3>Outcomes and Results</h3>
            <p>
              These projects were challenging, but my favorite to work on throughout my graduate degreee. I was able to develop finite element equations for the governeing equations for common PDEs (including heat transfer
              and stress analysis) to assembling element equations to a global system of equations for scalar/vector field problems. On top of that, I was able to compare my finite elements solutions accuracy compared to the
              governing equations alongside commercial softwares. I thought it was super interesting to learn about what happens behind the scenes in commercial finite element codes, and to see if I could replicate the results manually. 
            </p>
          </div>

          <div className="detail-section">
            <h3>Reflection</h3>
            <p>
              I hope to leverage the knowledge I gained from this class in my career. The power of the finite element method is unparalled in my eyes in the context of mechanical engineering, and I find
              great satisfaction in producing accurate simulations that validate a design. Gaining a deeper understanding of the governing equations in a process and what the code is actually doing I 
              think is invaluable to an analysis engineer's ability to ensure a finite element simualation is actually informative and not just pretty colors. Having the ability to see into the future is
              awesome, and I plan to lean more into this field. 
            </p>
          </div>
        </div>
      </div>
      
      <ImageModal
        isOpen={modalState.isOpen}
        imageSrc={modalState.imageSrc}
        imageAlt={modalState.imageAlt}
        onClose={closeModal}
      />
    </div>
  );
}

export default FiniteElementCodingCourseProjects;
